version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    restart: always
    environment:
      - ULTRAMSG_TOKEN=${ULTRAMSG_TOKEN}
      - ULTRAMSG_INSTANCE_ID=${ULTRAMSG_INSTANCE_ID}
      - API_PORT=${API_PORT}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB=${MONGO_DB}
      - JWT_SECRET=${JWT_SECRET}
      - RESEND_API_KEY=${RESEND_API_KEY}
    depends_on:
      - mongodb
    ports:
      - "3001:3001"
    links:
      - mongodb

  mongodb:
    image: mongo:8
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    ports:
      - "27017:27017"

volumes:
  mongodb_data:
