services:
  backend:
    build: .
    container_name: backend
    env_file:
      - .env
    ports:
      - "${API_PORT}:3001"
    networks:
      - openwa-network
    environment:
      - ULTRAMSG_TOKEN=${ULTRAMSG_TOKEN}
      - ULTRAMSG_INSTANCE_ID=${ULTRAMSG_INSTANCE_ID}
      - API_PORT=${API_PORT}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB=${MONGO_DB}
      - JWT_SECRET=${JWT_SECRET}
      - RESEND_API_KEY=${RESEND_API_KEY}

    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    networks:
      - openwa-network
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    external: true
    name: ivcarcobranzas-back_mongo_data

networks:
  openwa-network:
    name: openwa-network
    external: true
