version: "3.8"

services:
  backend:
    image: node:20
    build: .
    container_name: backend
    links:
      - mongodb
    volumes:
      - ./src:/home/node/app/src # Solo montar el código fuente, no sobrescribir todo
    ports:
      - "${API_PORT}:3001"
    command: npm run start
    environment:
      - ULTRAMSG_TOKEN=${ULTRAMSG_TOKEN}
      - ULTRAMSG_INSTANCE_ID=${ULTRAMSG_INSTANCE_ID}
      - API_PORT=${API_PORT}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB=${MONGO_DB}
      - JWT_SECRET=${JWT_SECRET}
      - RESEND_API_KEY=${RESEND_API_KEY}

    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - mongodb_data:/data/db # Persistencia de datos

volumes:
  mongodb_data: # Volumen para guardar los datos de MongoDB
